apiVersion: v1
kind: Service
metadata:
  name: angular
spec:
  type: NodePort
  selector:
    app: angular
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000  # Adjust the nodePort as needed
